name: moneysave
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_swiper_view: ^1.1.8
  fl_chart: ^0.62.0
  provider: ^6.1.2
  dots_indicator: 3.0.0
  syncfusion_flutter_sliders:  ^22.2.8
  font_awesome_flutter: ^10.6.0
  syncfusion_flutter_core:  ^22.2.8
  syncfusion_flutter_charts:  ^22.2.8
  flutter_svg: ^2.0.10+1
  progresso: ^0.3.0
  percent_indicator: ^4.2.3
  mask_text_input_formatter: ^2.9.0
  animated_bottom_navigation_bar: ^1.3.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - images/
    




  fonts:
    - family: QuickSand
      fonts:
        - asset: fonts/google_fonts/Quicksand-Light.ttf 
        - asset: fonts/google_fonts/Quicksand-Bold.ttf
        - asset: fonts/google_fonts/Quicksand-Medium.ttf
        - asset: fonts/google_fonts/Quicksand-Regular.ttf
        - asset: fonts/google_fonts/Quicksand-SemiBold.ttf
    - family: Rajdhani
      fonts:
        - asset: fonts/google_fonts/Rajdhani-Light.ttf
        - asset: fonts/google_fonts/Rajdhani-Bold.ttf
        - asset: fonts/google_fonts/Rajdhani-Medium.ttf
        - asset: fonts/google_fonts/Rajdhani-Regular.ttf
        - asset: fonts/google_fonts/Rajdhani-SemiBold.ttf

  
